name: CI/CD Buildozer Android

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip3 install --upgrade pip
        pip3 install --user --upgrade cython==0.29.36 buildozer

    - name: Build with Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer -v android debug

    - name: List bin directory
      run: ls -la bin/

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tactical-scanner-apk
        path: bin/*.apk
